{{- if .Values.services.mlops_platform.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-platform
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.mlops_platform.replicas }}
  selector:
    matchLabels:
    app: mlops-platform
  template:
    metadata:
    labels:
        app: mlops-platform
        {{- include "linkops.labels" . | nindent 8 }}
      {{- with .Values.global.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.security.rbac.createServiceAccounts }}
      serviceAccountName: mlops-platform-sa
      {{- end }}
      {{- with .Values.affinity.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
    - name: mlops-platform
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.mlops_platform.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.mlops_platform.port }}
          protocol: TCP
        {{- if .Values.services.mlops_platform.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.mlops_platform.healthCheck.path }}
            port: {{ .Values.services.mlops_platform.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.mlops_platform.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mlops_platform.healthCheck.periodSeconds }}
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.services.mlops_platform.healthCheck.path }}
            port: {{ .Values.services.mlops_platform.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.mlops_platform.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mlops_platform.healthCheck.periodSeconds }}
          timeoutSeconds: 5
          failureThreshold: 3
        {{- end }}
        {{- with .Values.services.mlops_platform.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.global.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.mlops_platform.resources | nindent 10 }}
        {{- with .Values.global.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
    - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
    - name: config
        configMap:
          name: mlops-platform-config
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-platform
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.mlops_platform.port }}
    protocol: TCP
  selector:
    app: mlops-platform

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-platform-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
data:
  config.yaml: |
    database:
    url: "postgresql://mlops:password@postgres:5432/mlops"
    redis:
    url: "redis://redis:6379"
    logging:
    level: INFO
      format: json

{{- if .Values.services.mlops_platform.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-platform
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
  {{- with .Values.services.mlops_platform.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.services.mlops_platform.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.services.mlops_platform.ingress.host }}
    http:
    paths:
    - path: /
        pathType: Prefix
        backend:
          service:
            name: mlops-platform
            port:
              number: 80
{{- end }}

{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-platform-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-platform
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
    name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
    name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}

{{- if .Values.security.rbac.createServiceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-platform-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlops-platform-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlops-platform-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: mlops-platform-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mlops-platform-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.security.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mlops-platform-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: mlops-platform
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    app: mlops-platform
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
    port: {{ .Values.services.mlops_platform.port }}
  - from:
    - podSelector:
        matchLabels:
          app: audit-assess
    ports:
    - protocol: TCP
    port: {{ .Values.services.mlops_platform.port }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
    port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
    port: 6379
  - to: []
    ports:
    - protocol: TCP
    port: 443
    - protocol: TCP
    port: 80
{{- end }}

{{- end }} 
