apiVersion: v1
kind: Secret
metadata:
  name: whis-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.services.whis_data_input.env | pluck "valueFrom" | first | default "dGVzdC1hcGkta2V5" | b64enc }}
  openai-api-key: {{ .Values.services.whis_enhance.env | pluck "valueFrom" | first | default "c2stdGVzdC1vcGVuYWktYXBpLWtleQ==" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: audit-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  gitguardian-api-key: {{ .Values.services.audit_assess.env | pluck "valueFrom" | first | default "Z2ctdGVzdC1naXRndWFyZGlhbi1hcGkta2V5" | b64enc }}
  snyk-token: {{ .Values.services.audit_assess.env | pluck "valueFrom" | last | default "c255ay10ZXN0LXRva2Vu" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.infrastructure.postgres.env | pluck "valueFrom" | first | default "bWxvcHMtcGFzc3dvcmQ=" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.monitoring.grafana.env | pluck "valueFrom" | first | default "Z3JhZmFuYS1hZG1pbi1wYXNzd29yZA==" | b64enc }} 
