apiVersion: v1
kind: Secret
metadata:
  name: whis-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: "{{ 'dGVzdC1hcGkta2V5' | b64enc }}"
  openai-api-key: "{{ 'c2stdGVzdC1vcGVuYWktYXBpLWtleQ==' | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: audit-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  gitguardian-api-key: "{{ 'Z2ctdGVzdC1naXRndWFyZGlhbi1hcGkta2V5' | b64enc }}"
  snyk-token: "{{ 'c255ay10ZXN0LXRva2Vu' | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ 'bWxvcHMtcGFzc3dvcmQ=' | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkops.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ "Z3JhZmFuYS1hZG1pbi1wYXNzd29yZA==" | b64enc }} 
