{{- if .Values.services.whis_data_input.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis-data-input
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-data-input
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.whis_data_input.replicas }}
  selector:
    matchLabels:
    app: whis-data-input
  template:
    metadata:
    labels:
        app: whis-data-input
        {{- include "linkops.labels" . | nindent 8 }}
    spec:
    containers:
    - name: whis-data-input
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.whis_data_input.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.whis_data_input.port }}
          protocol: TCP
        {{- if .Values.services.whis_data_input.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.whis_data_input.healthCheck.path }}
            port: {{ .Values.services.whis_data_input.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_data_input.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_data_input.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.whis_data_input.healthCheck.path }}
            port: {{ .Values.services.whis_data_input.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_data_input.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_data_input.healthCheck.periodSeconds }}
        {{- end }}
        {{- with .Values.services.whis_data_input.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.whis_data_input.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: whis-data-input
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-data-input
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.whis_data_input.port }}
    protocol: TCP
  selector:
    app: whis-data-input
{{- end }}

{{- if .Values.services.whis_sanitize.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis-sanitize
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-sanitize
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.whis_sanitize.replicas }}
  selector:
    matchLabels:
    app: whis-sanitize
  template:
    metadata:
    labels:
        app: whis-sanitize
        {{- include "linkops.labels" . | nindent 8 }}
    spec:
    containers:
    - name: whis-sanitize
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.whis_sanitize.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.whis_sanitize.port }}
          protocol: TCP
        {{- if .Values.services.whis_sanitize.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.whis_sanitize.healthCheck.path }}
            port: {{ .Values.services.whis_sanitize.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_sanitize.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_sanitize.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.whis_sanitize.healthCheck.path }}
            port: {{ .Values.services.whis_sanitize.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_sanitize.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_sanitize.healthCheck.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.whis_sanitize.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: whis-sanitize
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-sanitize
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.whis_sanitize.port }}
    protocol: TCP
  selector:
    app: whis-sanitize
{{- end }}

{{- if .Values.services.whis_smithing.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis-smithing
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-smithing
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.whis_smithing.replicas }}
  selector:
    matchLabels:
    app: whis-smithing
  template:
    metadata:
    labels:
        app: whis-smithing
        {{- include "linkops.labels" . | nindent 8 }}
    spec:
    containers:
    - name: whis-smithing
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.whis_smithing.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.whis_smithing.port }}
          protocol: TCP
        {{- if .Values.services.whis_smithing.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.whis_smithing.healthCheck.path }}
            port: {{ .Values.services.whis_smithing.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_smithing.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_smithing.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.whis_smithing.healthCheck.path }}
            port: {{ .Values.services.whis_smithing.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_smithing.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_smithing.healthCheck.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.whis_smithing.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: whis-smithing
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-smithing
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.whis_smithing.port }}
    protocol: TCP
  selector:
    app: whis-smithing
{{- end }}

{{- if .Values.services.whis_enhance.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis-enhance
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-enhance
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.whis_enhance.replicas }}
  selector:
    matchLabels:
    app: whis-enhance
  template:
    metadata:
    labels:
        app: whis-enhance
        {{- include "linkops.labels" . | nindent 8 }}
    spec:
    containers:
    - name: whis-enhance
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.whis_enhance.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.whis_enhance.port }}
          protocol: TCP
        {{- if .Values.services.whis_enhance.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.whis_enhance.healthCheck.path }}
            port: {{ .Values.services.whis_enhance.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_enhance.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_enhance.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.whis_enhance.healthCheck.path }}
            port: {{ .Values.services.whis_enhance.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_enhance.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_enhance.healthCheck.periodSeconds }}
        {{- end }}
        {{- with .Values.services.whis_enhance.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.whis_enhance.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: whis-enhance
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-enhance
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.whis_enhance.port }}
    protocol: TCP
  selector:
    app: whis-enhance
{{- end }}

{{- if .Values.services.whis_webscraper.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis-webscraper
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-webscraper
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.whis_webscraper.replicas }}
  selector:
    matchLabels:
    app: whis-webscraper
  template:
    metadata:
    labels:
        app: whis-webscraper
        {{- include "linkops.labels" . | nindent 8 }}
    spec:
    containers:
    - name: whis-webscraper
        image: {{ .Values.global.imageRegistry }}/{{ .Values.global.imageRepository }}/{{ .Values.services.whis_webscraper.image }}:{{ .Values.global.imageTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
    - name: http
          containerPort: {{ .Values.services.whis_webscraper.port }}
          protocol: TCP
        {{- if .Values.services.whis_webscraper.healthCheck }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.whis_webscraper.healthCheck.path }}
            port: {{ .Values.services.whis_webscraper.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_webscraper.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_webscraper.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.whis_webscraper.healthCheck.path }}
            port: {{ .Values.services.whis_webscraper.healthCheck.port }}
          initialDelaySeconds: {{ .Values.services.whis_webscraper.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.whis_webscraper.healthCheck.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.services.whis_webscraper.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: whis-webscraper
  namespace: {{ .Release.Namespace }}
  labels:
    app: whis-webscraper
    {{- include "linkops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.services.whis_webscraper.port }}
    protocol: TCP
  selector:
    app: whis-webscraper
{{- end }} 
