{{- if and .Values.rbac.create .Values.rbac.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "igris-logic.fullname" . }}-role
  labels:
    {{- include "igris-logic.labels" . | nindent 4 }}
rules:
  # Platform engineering operations
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  # Infrastructure analysis
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]

  # Security assessment
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  # OpenDevin integration
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "igris-logic.fullname" . }}-role-binding
  labels:
    {{- include "igris-logic.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "igris-logic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "igris-logic.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
