{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "katie-logic.fullname" . }}-cluster-role
  labels:
    {{- include "katie-logic.labels" . | nindent 4 }}
rules:
  # Full cluster access for Katie's guardian role
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["policy"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}

{{- if and .Values.rbac.create .Values.rbac.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "katie-logic.fullname" . }}-cluster-role-binding
  labels:
    {{- include "katie-logic.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "katie-logic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "katie-logic.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
