extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  line-length:
    max: 140
  indentation:
    spaces: 4
    indent-sequences: true
  empty-lines:
    max: 1
