version: '3.8'

services:
  # LinkOps Core Application (Backend)
  core:
    build:
      context: ./core
    container_name: linkops-core
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/linkops
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: linkops-postgres
    environment:
      POSTGRES_DB: linkops
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
