# Docker Compose Build Configuration for LinkOps Demo Images
# This file is used to build and push all demo images to Docker Hub
version: '3.9'

services:
  # Frontend Application
  demo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: linksrobot/demo-frontend:latest

  # Whis Data Input Service
  demo-whis-data-input:
    build:
      context: ./mlops/whis-data-input
      dockerfile: Dockerfile
    image: linksrobot/demo-whis-data-input:latest

  # Whis Sanitize Service
  demo-whis-sanitize:
    build:
      context: ./mlops/whis-sanitize
      dockerfile: Dockerfile
    image: linksrobot/demo-whis-sanitize:latest

  # Whis Logic Service
  demo-whis-logic:
    build:
      context: ./mlops/whis-logic
      dockerfile: Dockerfile
    image: linksrobot/demo-whis-logic:latest

  # Ficknury Evaluator Service
  demo-ficknury-evaluator:
    build:
      context: ./shadows/ficknury-evaluator
      dockerfile: Dockerfile
    image: linksrobot/demo-ficknury-evaluator:latest

  # MLOps Platform Service (if it has a Dockerfile)
  demo-mlops-platform:
    build:
      context: ./mlops/mlops-platform
      dockerfile: Dockerfile
    image: linksrobot/demo-mlops-platform:latest
    profiles:
      - optional  # Only build if Dockerfile exists 