version: '3.8'

services:
  # Unified API Service - Main orchestration service
  unified-api:
    build:
      context: ./unified-api
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-unified-api:${IMAGE_TAG:-latest}
    container_name: demo-linkops-api
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_NAME=unified-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./db:/app/db
      - ./rag_data:/app/rag_data
      - ./unified-api:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - demo-linkops-network

  # Frontend Service - Vue.js Interface
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-frontend:${IMAGE_TAG:-latest}
    container_name: demo-linkops-ui
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:${API_PORT:-8000}
      - NODE_ENV=production
      - SERVICE_NAME=frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      unified-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - demo-linkops-network

  # RAG Service - Search & Retrieval
  rag:
    build:
      context: ./rag
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-rag:${IMAGE_TAG:-latest}
    container_name: demo-linkops-rag
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - RAG_MODEL=${RAG_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_NAME=rag
    volumes:
      - ./db:/app/db
      - ./rag_data:/app/rag_data
      - ./rag:/app
    ports:
      - "8001:8001"
    depends_on:
      - unified-api
    restart: unless-stopped
    networks:
      - demo-linkops-network

  # ML Models Service - Machine Learning Operations
  ml-models:
    build:
      context: ./ml-models
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-ml-models:${IMAGE_TAG:-latest}
    container_name: demo-linkops-ml
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_NAME=ml-models
    volumes:
      - ./db:/app/db
      - ./ml-models:/app
    ports:
      - "8002:8002"
    depends_on:
      - unified-api
    restart: unless-stopped
    networks:
      - demo-linkops-network

  # Pipeline Service - Data Processing
  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-pipeline:${IMAGE_TAG:-latest}
    container_name: demo-linkops-pipeline
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_NAME=pipeline
    volumes:
      - ./db:/app/db
      - ./pipeline:/app
    ports:
      - "8003:8003"
    depends_on:
      - unified-api
    restart: unless-stopped
    networks:
      - demo-linkops-network

  # Sync Engine Service - Data Synchronization (Optional)
  sync-engine:
    build:
      context: ./sync_engine
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-linksrobot}/demo-sync-engine:${IMAGE_TAG:-latest}
    container_name: demo-linkops-sync
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVICE_NAME=sync-engine
    volumes:
      - ./db:/app/db
      - ./sync_engine:/app
      - ./sync_engine/watch:/watch
    depends_on:
      - unified-api
      - rag
    restart: unless-stopped
    networks:
      - demo-linkops-network
    profiles:
      - sync

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ai-box-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - ai-box-network

  # Optional: PostgreSQL for production (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: ai-box-db
  #   environment:
  #     - POSTGRES_DB=ai_box
  #     - POSTGRES_USER=ai_box_user
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-ai_box_password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - ai-box-network

  # Optional: Nginx reverse proxy (uncomment for production)
  # nginx:
  #   image: nginx:alpine
  #   container_name: ai-box-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - frontend
  #     - unified-api
  #   restart: unless-stopped
  #   networks:
  #     - ai-box-network

networks:
  demo-linkops-network:
    driver: bridge
    name: demo-linkops-network
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  # Uncomment if using Redis
  # redis_data:
  
  # Uncomment if using PostgreSQL
  # postgres_data:
  
  # Placeholder to avoid empty volumes section
  demo_volumes_placeholder: 