version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Expose container port 80 to localhost:8080
    depends_on:
      - mlops-platform
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  mlops-platform:
    build: ./mlops/mlops-platform
    ports:
      - "8000:8000"
    volumes:
      - ./mlops/mlops-platform/data:/app/data
    environment:
      - ENVIRONMENT=production

  whis-data-input:
    build: ./mlops/whis-data-input
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=production

  whis-logic:
    build: ./mlops/whis-logic
    ports:
      - "8002:8000"
    environment:
      - ENVIRONMENT=production

  whis-sanitize:
    build: ./mlops/whis-sanitize
    ports:
      - "8003:8000"
    environment:
      - ENVIRONMENT=production

  whis-ml:
    build: ./mlops/whis-ml
    ports:
      - "8004:8000"
    volumes:
      - ./mlops/whis-ml/dataset:/app/dataset
      - ./mlops/whis-ml/training_orbs:/app/training_orbs
      - ./mlops/whis-ml/backups:/app/backups
    environment:
      - ENVIRONMENT=production
    command: ["python", "infer.py"] 

  ficknury-evaluator:
    build: ./shadows/ficknury-evaluator
    ports:
      - "8005:8000"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - mlops-platform 