version: "3.8"

services:
  ### 🗄️ POSTGRESQL
  postgres:
    image: postgres:16
    container_name: linkops-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: linkops
      POSTGRES_USER: linkops
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-linkops_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ### 🔧 BACKEND (FastAPI)
  backend:
    build:
      context: ./backend
    container_name: linkops-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://linkops:${POSTGRES_PASSWORD:-linkops_password}@postgres:5432/linkops
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - kafka

  ### 🧠 FRONTEND (Vue Dev Server)
  frontend:
    build:
      context: ./frontend
    container_name: linkops-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

  ### 🦁 ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: linkops-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log

  ### 📡 KAFKA (Zookeeper Mode)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: linkops-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  ### 📥 WHIS DATA INPUT SERVICE (formerly data_collector)
  whis_data_input:
    build: ./services/whis_data_input
    container_name: linkops-whis-data-input
    ports:
      - "8001:8000"
    volumes:
      - ./services/whis_data_input:/app
    environment:
      - KAFKA_BROKERS=kafka:9092
      - SANITIZER_URL=http://whis_sanitize:8000/api/sanitize
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - kafka

  ### 🧹 WHIS SANITIZE SERVICE (formerly sanitizer)
  whis_sanitize:
    build: ./services/whis_sanitize
    container_name: linkops-whis-sanitize
    ports:
      - "8002:8000"
    volumes:
      - ./services/whis_sanitize:/app
      - ./data_lake:/app/data_lake
    environment:
      - SMITHING_URL=http://whis_smithing:8000/api/v1/smithing/generate-rune
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🔨 WHIS SMITHING SERVICE (new - rune/orb logic)
  whis_smithing:
    build: ./services/whis_smithing
    container_name: linkops-whis-smithing
    ports:
      - "8004:8000"
    volumes:
      - ./services/whis_smithing:/app
    environment:
      - ENHANCE_URL=http://whis_enhance:8000/api/v1/enhance/train-agent
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🚀 WHIS ENHANCE SERVICE (new - agent enhancement)
  whis_enhance:
    build: ./services/whis_enhance
    container_name: linkops-whis-enhance
    ports:
      - "8005:8000"
    volumes:
      - ./services/whis_enhance:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🧠 WHIS LOGIC SOURCE (ML Training Logic)
  whis_logic:
    build: ./services/whis_logic
    container_name: linkops-whis-logic
    ports:
      - "8003:8000"
    volumes:
      - ./services/whis_logic:/app
      - ./data_lake:/app/data_lake
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🤖 FICKNURY AGENT COMMANDER SERVICE
  ficknury:
    build: ./services/ficknury
    container_name: linkops-ficknury
    ports:
      - "8010:8000"
    volumes:
      - ./services/ficknury:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🕷️ WHIS WEBSCRAPER INTELLIGENCE HARVESTER
  whis_webscraper:
    build: ./services/whis_webscraper
    container_name: linkops-whis-webscraper
    ports:
      - "8011:8009"
    volumes:
      - ./services/whis_webscraper:/app
      - ./logs:/app/logs
    environment:
      - SANITIZE_SERVICE_URL=http://whis_sanitize:8000
      - LOGS_BASE_PATH=/app/logs
    depends_on:
      - whis_sanitize
    networks:
      - linkops-network

  ### 🧠 JAMES LOGIC SOURCE (AI Assistant Logic)
  james_logic:
    build: ./services/james_logic
    container_name: linkops-james-logic
    ports:
      - "8006:8000"
    volumes:
      - ./services/james_logic:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🛡️ AUDITGUARD SECURITY & COMPLIANCE SERVICE
  auditguard:
    build: ./services/auditguard
    container_name: linkops-auditguard
    ports:
      - "8007:8000"
    volumes:
      - ./services/auditguard:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### 🏗️ IGRIS LOGIC SOURCE (Platform Engineering Logic)
  igris_logic:
    build: ./services/igris_logic
    container_name: linkops-igris-logic
    ports:
      - "8009:8000"
    volumes:
      - ./services/igris_logic:/app
      - ~/.aws:/root/.aws
      - ~/.azure:/root/.azure
    environment:
      - AWS_PROFILE=default
      - AZURE_PROFILE=default
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ### ☸️ KATIE LOGIC SOURCE (Kubernetes Operations Logic)
  katie_logic:
    build: ./services/katie_logic
    container_name: linkops-katie-logic
    ports:
      - "8008:8000"
    volumes:
      - ./services/katie_logic:/app
      - ~/.kube:/root/.kube
    environment:
      - KUBECONFIG=/root/.kube/config
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:
  zookeeper_logs: 