apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "whis-sanitize.fullname" .}}
  labels:
    {{- include "whis-sanitize.labels" . | nindent 4}}
spec:
  {{- if not .Values.autoscaling.enabled}}
  replicas: {{.Values.replicaCount}}
  {{- end}}
  selector:
    matchLabels:
      {{- include "whis-sanitize.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      labels:
        {{- include "whis-sanitize.selectorLabels" . | nindent 8}}
    spec:
      {{- with .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end}}
      serviceAccountName: {{include "whis-sanitize.serviceAccountName" .}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}
      containers:
        - name: {{.Chart.Name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          env:
            {{- range .Values.env}}
            - name: {{.name}}
              {{- if .value}}
              value: {{.value | quote}}
              {{- end}}
              {{- if .valueFrom}}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16}}
              {{- end}}
            {{- end}}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12}}
      {{- with .Values.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.affinity}}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.tolerations}}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}
