apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-linkops.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "demo-linkops.name" . }}
    component: frontend
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.port }} 