<template>
  <div class="james-gui">
    <div class="gui-header">
      <h2 class="gui-title">🧠 James GUI - Task Processing</h2>
      <p class="gui-subtitle">Submit tasks and manage Orbs (best practices)</p>
    </div>

    <!-- Task Input Section -->
    <div class="task-input-section">
      <h3 class="section-title">📝 Task Input</h3>
      <div class="input-container">
        <textarea
          v-model="taskInput"
          placeholder="Enter your task description here... (e.g., 'How do I deploy a Kubernetes application?')"
          class="task-textarea"
          rows="4"
        ></textarea>
        <div class="input-actions">
          <button
            @click="submitTask"
            :disabled="!taskInput.trim() || processing"
            class="btn-primary"
          >
            <span v-if="processing" class="loading-spinner"></span>
            {{ processing ? 'Processing...' : 'Submit Task' }}
          </button>
          <button @click="clearTask" class="btn-secondary">Clear</button>
        </div>
      </div>
    </div>

    <!-- Results Section -->
    <div v-if="currentResult" class="results-section">
      <h3 class="section-title">📊 Processing Results</h3>

      <!-- Search Results -->
      <div v-if="currentResult.searchResults" class="result-card">
        <h4>🔍 Orb Library Search</h4>
        <div
          v-if="currentResult.searchResults.length > 0"
          class="search-results"
        >
          <div
            v-for="(orb, index) in currentResult.searchResults"
            :key="index"
            class="orb-item"
          >
            <h5>{{ orb.title }}</h5>
            <p>{{ orb.description }}</p>
            <div class="orb-meta">
              <span class="meta-tag">Match Score: {{ orb.matchScore }}%</span>
              <span class="meta-tag">Category: {{ orb.category }}</span>
            </div>
          </div>
        </div>
        <div v-else class="no-results">
          <p>No matching Orbs found in the library.</p>
        </div>
      </div>

      <!-- Generated Orb -->
      <div v-if="currentResult.generatedOrb" class="result-card">
        <h4>✨ Generated Orb</h4>
        <div class="generated-orb">
          <h5>{{ currentResult.generatedOrb.title }}</h5>
          <p>{{ currentResult.generatedOrb.description }}</p>
          <div class="orb-content">
            <h6>Best Practice Steps:</h6>
            <ol>
              <li
                v-for="(step, index) in currentResult.generatedOrb.steps"
                :key="index"
              >
                {{ step }}
              </li>
            </ol>
          </div>
          <div class="orb-meta">
            <span class="meta-tag">Generated by: Whis Logic</span>
            <span class="meta-tag">AI Model: Grok API</span>
          </div>
        </div>

        <!-- Approval Actions -->
        <div class="approval-actions">
          <button @click="approveOrb" class="btn-success">
            ✅ Approve & Save
          </button>
          <button @click="rejectOrb" class="btn-danger">❌ Reject</button>
        </div>
      </div>

      <!-- Rejection Message -->
      <div v-if="showRejectionMessage" class="result-card rejection-message">
        <h4>⚠️ Demo Limitation</h4>
        <p>
          <strong>The demo version doesn't support refinement.</strong> In the
          full version, the task would have been sent back through the learning
          loop with additional input and feedback for improvement.
        </p>
        <button @click="showRejectionMessage = false" class="btn-secondary">
          Dismiss
        </button>
      </div>
    </div>

    <!-- Recent Orbs -->
    <div v-if="recentOrbs.length > 0" class="recent-orbs-section">
      <h3 class="section-title">📚 Recent Orbs</h3>
      <div class="orbs-grid">
        <div v-for="orb in recentOrbs" :key="orb.id" class="orb-card">
          <h5>{{ orb.title }}</h5>
          <p>{{ orb.description }}</p>
          <div class="orb-meta">
            <span class="meta-tag">{{ orb.category }}</span>
            <span class="meta-tag">{{ orb.createdAt }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Demo Info -->
    <div class="demo-info">
      <h3 class="section-title">ℹ️ Demo Information</h3>
      <div class="info-grid">
        <div class="info-card">
          <h4>🎯 What This Demo Shows</h4>
          <ul>
            <li>Task input and processing</li>
            <li>Orb library searching</li>
            <li>AI-powered Orb generation</li>
            <li>Approval workflow</li>
          </ul>
        </div>
        <div class="info-card">
          <h4>🚫 Demo Limitations</h4>
          <ul>
            <li>No refinement loop</li>
            <li>No autonomous execution</li>
            <li>No complex pipelines</li>
            <li>No training capabilities</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const taskInput = ref('');
const processing = ref(false);
const currentResult = ref(null);
const showRejectionMessage = ref(false);
const recentOrbs = ref([]);

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

const submitTask = async () => {
  if (!taskInput.value.trim() || processing.value) return;

  processing.value = true;
  currentResult.value = null;
  showRejectionMessage.value = false;

  try {
    // Step 1: Submit task
    const taskResponse = await axios.post(`${API_BASE}/api/task/submit`, {
      task: taskInput.value.trim(),
    });

    // Step 2: Search for existing Orbs
    const searchResponse = await axios.post(`${API_BASE}/api/orbs/search`, {
      query: taskInput.value.trim(),
    });

    // Step 3: If no matches, generate new Orb
    let generatedOrb = null;
    if (searchResponse.data.results.length === 0) {
      const generateResponse = await axios.post(
        `${API_BASE}/api/orbs/generate`,
        {
          task: taskInput.value.trim(),
        }
      );
      generatedOrb = generateResponse.data.orb;
    }

    currentResult.value = {
      task: taskInput.value.trim(),
      searchResults: searchResponse.data.results,
      generatedOrb: generatedOrb,
    };
  } catch (error) {
    console.error('Error processing task:', error);
    // Fallback for demo - create mock result
    currentResult.value = {
      task: taskInput.value.trim(),
      searchResults: [],
      generatedOrb: {
        title: `Best Practice for: ${taskInput.value.trim()}`,
        description: `AI-generated best practice for the submitted task.`,
        steps: [
          'Analyze the task requirements',
          'Identify key components and dependencies',
          'Follow industry best practices',
          'Implement with proper error handling',
          'Test and validate the solution',
        ],
      },
    };
  } finally {
    processing.value = false;
  }
};

const approveOrb = async () => {
  if (!currentResult.value?.generatedOrb) return;

  try {
    await axios.post(`${API_BASE}/api/orbs/approve`, {
      orb: currentResult.value.generatedOrb,
    });

    // Add to recent Orbs
    recentOrbs.value.unshift({
      id: Date.now(),
      ...currentResult.value.generatedOrb,
      category: 'Generated',
      createdAt: new Date().toLocaleDateString(),
    });

    // Clear current result
    currentResult.value = null;
    taskInput.value = '';
  } catch (error) {
    console.error('Error approving Orb:', error);
    // For demo, just add to local list
    recentOrbs.value.unshift({
      id: Date.now(),
      ...currentResult.value.generatedOrb,
      category: 'Generated',
      createdAt: new Date().toLocaleDateString(),
    });
    currentResult.value = null;
    taskInput.value = '';
  }
};

const rejectOrb = () => {
  showRejectionMessage.value = true;
  currentResult.value = null;
  taskInput.value = '';
};

const clearTask = () => {
  taskInput.value = '';
  currentResult.value = null;
  showRejectionMessage.value = false;
};

const loadRecentOrbs = async () => {
  try {
    const response = await axios.get(`${API_BASE}/api/orbs/recent`);
    recentOrbs.value = response.data.orbs;
  } catch (error) {
    console.error('Error loading recent Orbs:', error);
    // Mock data for demo
    recentOrbs.value = [
      {
        id: 1,
        title: 'Kubernetes Deployment Best Practices',
        description:
          'Standard practices for deploying applications to Kubernetes clusters.',
        category: 'DevOps',
        createdAt: '2024-01-15',
      },
      {
        id: 2,
        title: 'API Security Guidelines',
        description: 'Security best practices for RESTful API development.',
        category: 'Security',
        createdAt: '2024-01-14',
      },
    ];
  }
};

onMounted(() => {
  loadRecentOrbs();
});
</script>

<style scoped>
.james-gui {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.gui-header {
  text-align: center;
  margin-bottom: 2rem;
}

.gui-title {
  font-size: 2rem;
  font-weight: bold;
  color: #00d4ff;
  margin-bottom: 0.5rem;
}

.gui-subtitle {
  color: #888;
  font-size: 1.1rem;
}

.section-title {
  font-size: 1.5rem;
  font-weight: bold;
  color: #e0e0e0;
  margin-bottom: 1rem;
  border-bottom: 2px solid #00d4ff;
  padding-bottom: 0.5rem;
}

.task-input-section {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid #333;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}

.input-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.task-textarea {
  width: 100%;
  background: rgba(0, 0, 0, 0.5);
  border: 1px solid #555;
  border-radius: 4px;
  color: #e0e0e0;
  padding: 1rem;
  font-size: 1rem;
  resize: vertical;
}

.task-textarea:focus {
  outline: none;
  border-color: #00d4ff;
  box-shadow: 0 0 10px rgba(0, 212, 255, 0.3);
}

.input-actions {
  display: flex;
  gap: 1rem;
}

.btn-primary,
.btn-secondary,
.btn-success,
.btn-danger {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 4px;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.3s ease;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.btn-primary {
  background: #00d4ff;
  color: #000;
}

.btn-primary:hover:not(:disabled) {
  background: #00b8e6;
  transform: translateY(-2px);
}

.btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-secondary {
  background: #666;
  color: #fff;
}

.btn-secondary:hover {
  background: #777;
}

.btn-success {
  background: #10b981;
  color: #fff;
}

.btn-success:hover {
  background: #059669;
}

.btn-danger {
  background: #ef4444;
  color: #fff;
}

.btn-danger:hover {
  background: #dc2626;
}

.loading-spinner {
  width: 16px;
  height: 16px;
  border: 2px solid transparent;
  border-top: 2px solid currentColor;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.results-section {
  margin-bottom: 2rem;
}

.result-card {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid #333;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1rem;
}

.result-card h4 {
  color: #00d4ff;
  margin-bottom: 1rem;
}

.search-results {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.orb-item {
  background: rgba(0, 0, 0, 0.2);
  border: 1px solid #444;
  border-radius: 4px;
  padding: 1rem;
}

.orb-item h5 {
  color: #e0e0e0;
  margin-bottom: 0.5rem;
}

.orb-item p {
  color: #ccc;
  margin-bottom: 0.5rem;
}

.orb-meta {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.meta-tag {
  background: #333;
  color: #ccc;
  padding: 0.25rem 0.5rem;
  border-radius: 4px;
  font-size: 0.8rem;
}

.no-results {
  text-align: center;
  color: #888;
  padding: 2rem;
}

.generated-orb {
  background: rgba(0, 212, 255, 0.1);
  border: 1px solid #00d4ff;
  border-radius: 4px;
  padding: 1rem;
  margin-bottom: 1rem;
}

.generated-orb h5 {
  color: #00d4ff;
  margin-bottom: 0.5rem;
}

.orb-content {
  margin: 1rem 0;
}

.orb-content h6 {
  color: #e0e0e0;
  margin-bottom: 0.5rem;
}

.orb-content ol {
  color: #ccc;
  padding-left: 1.5rem;
}

.orb-content li {
  margin-bottom: 0.5rem;
}

.approval-actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
  margin-top: 1rem;
}

.rejection-message {
  background: rgba(239, 68, 68, 0.1);
  border: 1px solid #ef4444;
}

.rejection-message h4 {
  color: #ef4444;
}

.recent-orbs-section {
  margin-bottom: 2rem;
}

.orbs-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1rem;
}

.orb-card {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid #333;
  border-radius: 8px;
  padding: 1rem;
}

.orb-card h5 {
  color: #e0e0e0;
  margin-bottom: 0.5rem;
}

.orb-card p {
  color: #ccc;
  margin-bottom: 0.5rem;
}

.demo-info {
  margin-top: 2rem;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1rem;
}

.info-card {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid #333;
  border-radius: 8px;
  padding: 1rem;
}

.info-card h4 {
  color: #00d4ff;
  margin-bottom: 1rem;
}

.info-card ul {
  color: #ccc;
  padding-left: 1.5rem;
}

.info-card li {
  margin-bottom: 0.5rem;
}

@media (max-width: 768px) {
  .james-gui {
    padding: 1rem;
  }

  .input-actions {
    flex-direction: column;
  }

  .approval-actions {
    flex-direction: column;
  }

  .orbs-grid {
    grid-template-columns: 1fr;
  }

  .info-grid {
    grid-template-columns: 1fr;
  }
}
</style>
