<template>
  <div class="p-6 space-y-6">
    <!-- Welcome Header -->
    <div class="text-center space-y-4">
      <h1 class="text-4xl font-bold bg-gradient-to-r from-purple-400 to-blue-500 bg-clip-text text-transparent">
        🛡️ DevSecOps Shadow Agent Demo
      </h1>
      <p class="text-lg text-gray-300 max-w-3xl mx-auto">
        This is a demonstration of one of the Shadow Agents developed by LinkOps, tailored specifically for DevSecOps workflows.
      </p>
    </div>

    <!-- Demo Mode Banner -->
    <div class="bg-yellow-200 text-yellow-900 text-center py-3 rounded-lg font-semibold">
      🎯 Demo Mode: Results are simulated. No real AI or API keys required.
    </div>

    <!-- Task Submission UI -->
    <div class="border border-gray-700 rounded-2xl p-6 bg-black/30">
      <h2 class="text-xl font-semibold mb-4 text-blue-400">🚀 Try It Now</h2>
      <label class="text-lg font-medium block mb-3">Task You Would Give Me</label>
      <textarea
        v-model="taskInput"
        placeholder="e.g., create a pod named test with image nginx, or scan repo for security vulnerabilities"
        class="w-full p-3 rounded-lg bg-black border border-gray-700 text-white resize-none"
        rows="3"
      ></textarea>
      <div class="flex justify-end mt-3 gap-3">
        <button
          @click="submitTask"
          :disabled="!taskInput.trim() || processing"
          class="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-6 py-3 rounded-xl hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 font-semibold"
        >
          <span v-if="processing" class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mx-auto"></span>
          {{ processing ? '🔍 Searching...' : '🔍 Search Orb' }}
        </button>
        <button @click="clearTask" class="bg-gray-700 text-white px-6 py-3 rounded-xl hover:bg-gray-600 font-semibold">
          Clear
        </button>
      </div>
    </div>

    <!-- Processing Results -->
    <div v-if="currentResult" class="space-y-4">
      <!-- Orb Results -->
      <div v-if="orbFound" class="border border-green-500 bg-black/20 p-6 rounded-2xl">
        <div class="flex items-center space-x-2 mb-4">
          <span class="text-2xl">✅</span>
          <h2 class="text-xl font-bold text-green-400">Orb Found!</h2>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <p><strong class="text-gray-300">Task:</strong> <span class="text-white">{{ taskInput }}</span></p>
            <p><strong class="text-gray-300">Matching Orb:</strong> <span class="text-green-400">{{ currentResult.searchResults[0].title }}</span></p>
            <p><strong class="text-gray-300">Match Score:</strong> <span class="text-yellow-400">{{ currentResult.searchResults[0].matchScore }}%</span></p>
            <p><strong class="text-gray-300">Category:</strong> <span class="text-blue-400">{{ currentResult.searchResults[0].category }}</span></p>
          </div>
          <div>
            <p><strong class="text-gray-300">Description:</strong></p>
            <p class="text-sm text-gray-300 mt-1">{{ currentResult.searchResults[0].description }}</p>
          </div>
        </div>
        <div class="mt-4 p-4 bg-gray-800 rounded-lg">
          <h3 class="text-lg font-bold text-green-300 mb-3">Best Practice Steps:</h3>
          <ul class="list-disc list-inside text-white space-y-1">
            <li v-for="(step, index) in currentResult.searchResults[0].steps" :key="index" class="text-sm">
              {{ step }}
            </li>
          </ul>
        </div>
        <div class="mt-4 space-y-2 text-sm">
          <p class="italic text-yellow-400">⚠️ Runes not available in demo. They are compiled solution path scripts.</p>
          <p class="italic text-yellow-400">⚠️ "Send to Agent?" → Feature not available in demo. FickNury sends tasks that are 100% autonomous to field agents.</p>
        </div>
      </div>

      <!-- Fallback Best Practice (Grok) -->
      <div v-else-if="generatedOrb" class="border border-blue-500 bg-black/20 p-6 rounded-2xl">
        <div class="flex items-center space-x-2 mb-4">
          <span class="text-2xl">✨</span>
          <h2 class="text-xl font-bold text-blue-400">No Orb Found - Generated Best Practice</h2>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <p><strong class="text-gray-300">Task:</strong> <span class="text-white">{{ taskInput }}</span></p>
            <p class="text-sm italic text-green-400 mt-2">🔄 Sent to Whis for Learning...</p>
          </div>
          <div>
            <p><strong class="text-gray-300">Generated by:</strong> <span class="text-purple-400">{{ currentResult.generatedOrb.demo_warning ? 'Demo Mode' : 'Whis Logic' }}</span></p>
            <p><strong class="text-gray-300">AI Model:</strong> <span class="text-blue-400">{{ currentResult.generatedOrb.demo_warning ? 'Simulated' : 'Grok API' }}</span></p>
          </div>
        </div>

        <!-- Demo Warning Banner -->
        <div
          v-if="currentResult.generatedOrb.demo_warning"
          class="bg-yellow-200 text-yellow-900 p-4 rounded-lg mt-4"
        >
          <div class="flex items-center space-x-2">
            <span class="text-xl">⚠️</span>
            <div>
              <strong>Demo Mode Response</strong>
              <p class="text-sm">No real AI processing occurred - this is a simulated response</p>
            </div>
          </div>
        </div>

        <div class="mt-4 p-4 bg-gray-800 rounded-lg">
          <h3 class="text-lg font-bold text-green-300 mb-3">Best Practice for: {{ taskInput }}</h3>
          <ul class="list-disc list-inside text-white space-y-1">
            <li v-for="(step, index) in currentResult.generatedOrb.steps" :key="index" class="text-sm">
              {{ step }}
            </li>
          </ul>
          <p class="text-xs text-gray-400 mt-3">Generated by: {{ currentResult.generatedOrb.demo_warning ? 'Demo Mode' : 'Whis Logic' }} | Model: {{ currentResult.generatedOrb.demo_warning ? 'Simulated' : 'Grok API' }}</p>
        </div>
        <div class="flex gap-3 mt-4">
          <button @click="approveOrb" class="px-4 py-2 rounded-lg bg-green-700 hover:bg-green-600 text-white font-semibold">
            ✅ Approve & Save
          </button>
          <button @click="rejectOrb" class="px-4 py-2 rounded-lg bg-red-700 hover:bg-red-600 text-white font-semibold">
            ❌ Reject
          </button>
        </div>
      </div>
    </div>

    <!-- Recent Orbs -->
    <div class="border border-gray-700 rounded-2xl p-6 bg-black/30">
      <h2 class="text-xl font-semibold mb-4 text-purple-400">📚 Recent Orbs</h2>
      <ul class="space-y-2">
        <li class="flex justify-between items-center">
          <div>
            <strong class="text-white">Kubernetes Deployment Best Practices</strong>
            <span class="text-xs text-gray-400 ml-2">(DevOps · 2024-01-15)</span>
          </div>
          <span class="text-green-400 text-sm">95% match</span>
        </li>
        <li class="flex justify-between items-center">
          <div>
            <strong class="text-white">API Security Guidelines</strong>
            <span class="text-xs text-gray-400 ml-2">(Security · 2024-01-14)</span>
          </div>
          <span class="text-green-400 text-sm">88% match</span>
        </li>
        <li class="flex justify-between items-center">
          <div>
            <strong class="text-white">Database Migration Best Practices</strong>
            <span class="text-xs text-gray-400 ml-2">(Database · 2024-01-13)</span>
          </div>
          <span class="text-green-400 text-sm">92% match</span>
        </li>
      </ul>
    </div>

    <!-- Purpose Section -->
    <div class="border border-gray-700 rounded-2xl p-6 bg-black/30">
      <h2 class="text-2xl font-bold mb-4 text-purple-400">💡 Purpose of This Demo</h2>
      <div class="space-y-3 text-gray-300">
        <p>• Show how tasks are matched to existing automation</p>
        <p>• Show fallback logic when task is new or incomplete</p>
        <p>• Educate on <strong>how</strong> the model learns and <strong>what tech</strong> powers it</p>
      </div>
      
      <div class="mt-6 p-4 bg-gray-800 rounded-lg">
        <h3 class="text-lg font-semibold text-yellow-400 mb-2">✅ What You Can Do Here</h3>
        <ul class="space-y-1 text-sm">
          <li class="flex items-center space-x-2">
            <span class="text-green-400">✅</span>
            <span>Submit tasks like you would in a real job</span>
          </li>
          <li class="flex items-center space-x-2">
            <span class="text-green-400">✅</span>
            <span>View how LinkOps agents rank automation readiness</span>
          </li>
          <li class="flex items-center space-x-2">
            <span class="text-red-400">❌</span>
            <span>No agent execution or full pipeline is available in this demo</span>
          </li>
        </ul>
      </div>
    </div>

    <!-- Rejection Message -->
    <div v-if="showRejectionMessage" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div class="bg-gray-800 border border-gray-600 rounded-lg p-6 max-w-md mx-4">
        <div class="flex justify-between items-center mb-4">
          <h4 class="text-lg font-bold text-red-400">🚫 Demo Limitation</h4>
          <button @click="showRejectionMessage = false" class="text-gray-400 hover:text-white text-xl">
            ×
          </button>
        </div>
        <div class="space-y-3">
          <p class="text-sm text-gray-300">
            <strong>This demo version does not support refinement or additional learning.</strong>
          </p>
          <p class="text-sm text-gray-300">
            In the full platform, this task would be re-sent with feedback through the full Whis pipeline for improvement.
          </p>
          <div class="flex justify-end">
            <button @click="showRejectionMessage = false" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import axios from 'axios';

// Reactive data
const taskInput = ref('');
const processing = ref(false);
const currentResult = ref(null);
const recentOrbs = ref([]);
const showRejectionMessage = ref(false);

// Computed properties
const orbFound = computed(() => {
  return (
    currentResult.value?.searchResults &&
    currentResult.value.searchResults.length > 0
  );
});

const generatedOrb = computed(() => {
  return currentResult.value?.generatedOrb;
});

// Methods
const submitTask = async () => {
  if (!taskInput.value.trim()) return;

  processing.value = true;
  currentResult.value = null;

  try {
    // First, search for existing Orbs
    const searchResponse = await axios.post('/api/orbs/search', {
      query: taskInput.value,
    });

    // If no matching Orbs found, generate a new one
    if (searchResponse.data.results.length === 0) {
      const generateResponse = await axios.post('/api/orbs/generate', {
        task: taskInput.value,
      });

      currentResult.value = {
        searchResults: [],
        generatedOrb: generateResponse.data.orb,
      };
    } else {
      currentResult.value = {
        searchResults: searchResponse.data.results,
        generatedOrb: null,
      };
    }
  } catch (error) {
    console.error('Error processing task:', error);
    // Fallback demo response
    currentResult.value = {
      searchResults: [],
      generatedOrb: {
        title: `Demo Response for: ${taskInput.value}`,
        description:
          '⚠️ Demo Mode: This is a simulated AI response. No real model was used.',
        steps: [
          '⚠️ Demo Mode Active - No Real AI Processing',
          'This response simulates what AI generation would look like',
          'To enable real AI capabilities, add your API key to the environment',
          'Supported models: Grok (xAI), OpenAI (ChatGPT), Anthropic (Claude)',
          'Contact the team for access to the full platform with real AI integration',
        ],
        demo_warning: true,
        demo_mode: true,
      },
    };
  } finally {
    processing.value = false;
  }
};

const clearTask = () => {
  taskInput.value = '';
  currentResult.value = null;
};

const approveOrb = async () => {
  if (!currentResult.value?.generatedOrb) return;

  try {
    await axios.post('/api/orbs/approve', {
      orb: currentResult.value.generatedOrb,
    });

    // Add to recent Orbs
    recentOrbs.value.unshift({
      id: Date.now(),
      title: currentResult.value.generatedOrb.title,
      description: currentResult.value.generatedOrb.description,
      category: currentResult.value.generatedOrb.category || 'Generated',
      createdAt: new Date().toISOString().split('T')[0],
    });

    // Clear current result
    currentResult.value = null;
  } catch (error) {
    console.error('Error approving Orb:', error);
  }
};

const rejectOrb = () => {
  showRejectionMessage.value = true;
};

// Lifecycle
onMounted(async () => {
  try {
    const response = await axios.get('/api/orbs/recent');
    recentOrbs.value = response.data.orbs || [];
  } catch (error) {
    console.error('Error loading recent Orbs:', error);
    // Fallback demo data
    recentOrbs.value = [
      {
        id: 1,
        title: 'Kubernetes Deployment Best Practices',
        description: 'Best practices for deploying applications to Kubernetes',
        category: 'DevOps',
        createdAt: '2024-01-15',
      },
      {
        id: 2,
        title: 'API Security Guidelines',
        description: 'Security best practices for API development',
        category: 'Security',
        createdAt: '2024-01-14',
      },
    ];
  }
});
</script>

<style scoped>
.demo-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  color: #e0e0e0;
  font-family: 'Orbitron', 'Courier New', monospace;
}

.text-xl {
  font-size: 1.5rem;
}

.text-lg {
  font-size: 1.25rem;
}

.text-md {
  font-size: 1.125rem;
}

.text-sm {
  font-size: 0.875rem;
}

.text-xs {
  font-size: 0.75rem;
}

.font-bold {
  font-weight: bold;
}

.font-semibold {
  font-weight: 600;
}

.mt-2 {
  margin-top: 0.5rem;
}

.mt-3 {
  margin-top: 0.75rem;
}

.mt-4 {
  margin-top: 1rem;
}

.mt-8 {
  margin-top: 2rem;
}

.mt-10 {
  margin-top: 2.5rem;
}

.ml-2 {
  margin-left: 0.5rem;
}

.ml-6 {
  margin-left: 1.5rem;
}

.mb-2 {
  margin-bottom: 0.5rem;
}

.pt-4 {
  padding-top: 1rem;
}

.text-gray-400 {
  color: #9ca3af;
}

.text-gray-500 {
  color: #6b7280;
}

.text-gray-300 {
  color: #d1d5db;
}

.text-blue-400 {
  color: #60a5fa;
}

.underline {
  text-decoration: underline;
}

.italic {
  font-style: italic;
}

.border-t {
  border-top: 1px solid #374151;
}

.textarea {
  width: 100%;
  background: rgba(0, 0, 0, 0.6);
  border: 1px solid #00d4ff;
  border-radius: 8px;
  padding: 1rem;
  color: #e0e0e0;
  font-family: inherit;
  resize: vertical;
  min-height: 100px;
}

.textarea:focus {
  outline: none;
  box-shadow: 0 0 10px rgba(0, 212, 255, 0.3);
}

.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  background: linear-gradient(45deg, #00d4ff, #0099cc);
  border: none;
  border-radius: 8px;
  color: white;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 0 20px rgba(0, 212, 255, 0.3);
}

.btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 10px 25px rgba(0, 212, 255, 0.4);
}

.btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-secondary {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  background: rgba(0, 0, 0, 0.6);
  border: 1px solid #00d4ff;
  border-radius: 8px;
  color: #00d4ff;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.3s ease;
}

.btn-secondary:hover {
  background: rgba(0, 212, 255, 0.1);
  transform: translateY(-2px);
  box-shadow: 0 10px 25px rgba(0, 212, 255, 0.3);
}

.loading-spinner {
  width: 16px;
  height: 16px;
  border: 2px solid transparent;
  border-top: 2px solid currentColor;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

.orb-item {
  background: rgba(0, 0, 0, 0.6);
  border: 1px solid #00d4ff;
  border-radius: 8px;
  padding: 1rem;
  backdrop-filter: blur(10px);
}

.generated-orb {
  background: rgba(0, 0, 0, 0.6);
  border: 1px solid #00d4ff;
  border-radius: 8px;
  padding: 1rem;
  backdrop-filter: blur(10px);
}

.demo-warning-banner {
  background: linear-gradient(135deg, #ffd700, #ffed4e);
  border: 2px solid #ff8c00;
  border-radius: 8px;
  padding: 1rem;
  display: flex;
  align-items: flex-start;
  gap: 1rem;
  box-shadow: 0 8px 25px rgba(255, 215, 0, 0.3);
}

.warning-icon {
  font-size: 1.5rem;
  min-width: 24px;
}

.warning-text {
  color: #8b4513;
}

.warning-text strong {
  display: block;
  margin-bottom: 0.25rem;
}

.warning-text span {
  font-size: 0.875rem;
}

.orb-meta {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
  margin-top: 1rem;
}

.meta-tag {
  background: rgba(0, 212, 255, 0.2);
  border: 1px solid #00d4ff;
  border-radius: 4px;
  padding: 0.25rem 0.5rem;
  font-size: 0.75rem;
  color: #00d4ff;
}

.list-disc {
  list-style-type: disc;
}

.rejection-popup-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.8);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.rejection-popup {
  background: rgba(0, 0, 0, 0.9);
  border: 2px solid #ff0000;
  border-radius: 12px;
  padding: 1.5rem;
  max-width: 500px;
  width: 90%;
  backdrop-filter: blur(10px);
}

.popup-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  border-bottom: 1px solid #ff0000;
  padding-bottom: 0.5rem;
}

.popup-header h4 {
  color: #ff0000;
  margin: 0;
}

.popup-close {
  background: none;
  border: none;
  color: #ff0000;
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.popup-content p {
  margin: 0.5rem 0;
  line-height: 1.5;
}

.popup-actions {
  margin-top: 1.5rem;
  text-align: right;
}

.btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  background: linear-gradient(45deg, #00d4ff, #0099cc);
  border: none;
  border-radius: 8px;
  color: white;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 0 20px rgba(0, 212, 255, 0.3);
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 10px 25px rgba(0, 212, 255, 0.4);
}

/* Responsive Design */
@media (max-width: 768px) {
  .demo-container {
    padding: 1rem;
  }

  .orb-meta {
    flex-direction: column;
    gap: 0.5rem;
  }

  .rejection-popup {
    width: 95%;
    margin: 1rem;
  }
}
</style>
