apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # echo -n "your_secure_password" | base64
  admin-password: "TGlua09wczIwMjQh"  # LinkOps2024! (base64 encoded) 