apiVersion: v1
kind: Secret
metadata:
  name: linkops-secrets
  namespace: linkops
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: "cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9saW5rb3Bz"  # postgresql://user:password@db:5432/linkops
  openai-api-key: "c2stZXhhbXBsZQ=="  # sk-example
  acr-username: "bGlua29wc2Fjcg=="  # linkopsacr
  acr-password: "ZXhhbXBsZQ=="  # example
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: linkops
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJsaW5rb3BzYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJsaW5rb3BzYWNyIiwicGFzc3dvcmQiOiJleGFtcGxlIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RPSJ9fX0=" 