apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "james-logic.fullname" . }}
  labels:
    {{- include "james-logic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "james-logic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "james-logic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "james-logic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.secrets.openai.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.openai.secretName }}
                  key: {{ .Values.secrets.openai.secretKey }}
            {{- end }}
            {{- if .Values.secrets.voice.enabled }}
            - name: VOICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.voice.secretName }}
                  key: {{ .Values.secrets.voice.secretKey }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.volumes.voice_cache.enabled }}
            - name: voice-cache
              mountPath: {{ .Values.volumes.voice_cache.mountPath }}
            {{- end }}
            {{- if .Values.volumes.image_cache.enabled }}
            - name: image-cache
              mountPath: {{ .Values.volumes.image_cache.mountPath }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.volumes.voice_cache.enabled }}
        - name: voice-cache
          {{- if .Values.volumes.voice_cache.emptyDir }}
          emptyDir: {}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.volumes.image_cache.enabled }}
        - name: image-cache
          {{- if .Values.volumes.image_cache.emptyDir }}
          emptyDir: {}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }} 