{{- if .Values.rbac.create }}
  {{- if .Values.rbac.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "james-logic.fullname" . }}-role
  labels:
    {{- include "james-logic.labels" . | nindent 4 }}
rules:
  # Assistant operations
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  # Voice and image processing
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  # Personal AI operations
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  {{- end }}

  {{- if .Values.rbac.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "james-logic.fullname" . }}-role-binding
  labels:
    {{- include "james-logic.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "james-logic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "james-logic.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
{{- end }}
