apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-unified-api
  namespace: demo-linkops
  labels:
    app: demo-unified-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-unified-api
  template:
    metadata:
      labels:
        app: demo-unified-api
    spec:
      containers:
      - name: unified-api
        image: localhost:5000/demo-linkops-unified-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: demo-linkops-config
        volumeMounts:
        - name: demo-db
          mountPath: /app/db
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 30
      volumes:
      - name: demo-db
        hostPath:
          path: /home/jimjrxieb/shadow-link-industries/DEMO-LinkOps/db
          type: Directory 