apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-linkops-ingress
  namespace: demo-linkops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: demo-unified-api
            port:
              number: 8000
      - path: /rag
        pathType: Prefix
        backend:
          service:
            name: demo-rag
            port:
              number: 8001 