apiVersion: v1
kind: Service
metadata:
  name: demo-rag
  namespace: demo-linkops
spec:
  type: ClusterIP
  selector:
    app: demo-rag
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-vectorstore-pvc
  namespace: demo-linkops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
  namespace: demo-linkops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 