apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rag
  namespace: demo-linkops
  labels:
    app: demo-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rag
  template:
    metadata:
      labels:
        app: demo-rag
    spec:
      containers:
      - name: rag
        image: localhost:5000/demo-linkops-rag:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: demo-linkops-config
        volumeMounts:
        - name: vectorstore-data
          mountPath: /app/data/vectorstore
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
      volumes:
      - name: vectorstore-data
        hostPath:
          path: /home/jimjrxieb/shadow-link-industries/DEMO-LinkOps/data/vectorstore
          type: DirectoryOrCreate 