apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "whis.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "whis.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"] 