apiVersion: v2
name: demo-stack
description: Umbrella chart for LinkOps demo platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: whis_data_input
    version: 0.1.0
    repository: "file://../whis_data_input"
  - name: whis_sanitize
    version: 0.1.0
    repository: "file://../whis_sanitize"
  - name: whis_logic
    version: 0.1.0
    repository: "file://../whis_logic"
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"
