  ### 📊 SCRAPERDASH INTELLIGENCE SERVICE
  scraperdash:
    build: ./services/scraperdash
    container_name: linkops-scraperdash
    ports:
      - "8005:8005"
    volumes:
      - ./services/scraperdash:/app
      - ./data_lake:/app/data_lake
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload
