apiVersion: v2
name: audit-assess
description: A Helm chart for Audit Assess microservice
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
- audit
- assess
- microservice
home: https://github.com/jimjrxieb/LinkOps-MLOps
sources:
- https://github.com/jimjrxieb/LinkOps-MLOps
maintainers:
- name: jimjrxieb
  email: jimjrxieb@example.com 
