apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "whis-kubeflow.serviceAccountName" . }}
  labels:
    {{- include "whis-kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }} 