# Default values for igris
replicaCount: 2

image:
  repository: ghcr.io/shadow-link-industries/igris
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: igris.shadow-link.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: igris-tls
      hosts:
        - igris.shadow-link.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "production"
  - name: PLATFORM_ENGINEERING_MODE
    value: "enabled"
  - name: SECURITY_SCANNING_ENABLED
    value: "true"

configMap:
  enabled: true
  data:
    platform_config.yaml: |
      platforms:
        kubernetes:
          enabled: true
          security_level: high
        aws:
          enabled: true
          security_level: high
        azure:
          enabled: true
          security_level: high
        gcp:
          enabled: true
          security_level: high

secret:
  enabled: true
  data:
    # Add any sensitive configuration here
    # Example: API keys, database credentials, etc. 