# Default values for igris-logic
replicaCount: 1

image:
  repository: ghcr.io/shadow-link-industries/igris_logic
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  role:
    create: true
    name: "igris-logic-role"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: igris-logic.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  LOG_LEVEL: "INFO"
  OPENAI_MODEL: "gpt-4"
  AWS_PROFILE: "default"
  AZURE_PROFILE: "default"

secrets:
  openai:
    enabled: true
    secretName: "openai-secret"
    secretKey: "key"
  aws:
    enabled: false
    secretName: "aws-credentials"
  azure:
    enabled: false
    secretName: "azure-credentials"

volumes:
  aws_config:
    enabled: false
    mountPath: "/root/.aws"
    secretName: "aws-config"
  azure_config:
    enabled: false
    mountPath: "/root/.azure"
    secretName: "azure-config"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 1000

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
