apiVersion: v2
name: whis-sanitize
description: A Helm chart for Whis Sanitize microservice
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
- whis
- sanitize
- microservice
home: https://github.com/jimjrxieb/LinkOps-MLOps
sources:
- https://github.com/jimjrxieb/LinkOps-MLOps
maintainers:
- name: jimjrxieb
  email: jimjrxieb@example.com 
