apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: linkops:apps/Deployment:linkops-demo/linkops-whis-logic
  labels:
    app.kubernetes.io/instance: linkops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: whis-logic
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: whis-logic-0.1.0
  name: linkops-whis-logic
  namespace: linkops-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: linkops
      app.kubernetes.io/name: whis-logic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: linkops
        app.kubernetes.io/name: whis-logic
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: INFO
            - name: SERVICE_PORT
              value: '8003'
          image: linksrobot/demo-whis-logic:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          name: whis-logic
          ports:
            - containerPort: 8003
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext: {}
      securityContext: {}
      serviceAccountName: linkops-whis-logic
