apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: linkops:apps/Deployment:linkops-demo/linkops-frontend
  labels:
    app.kubernetes.io/instance: linkops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: frontend-0.1.0
  name: linkops-frontend
  namespace: linkops-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: linkops
      app.kubernetes.io/name: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: linkops
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - env:
            - name: VITE_API_BASE_URL
              value: http://mlops-platform:8000
          image: linksrobot/demo-frontend:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          name: frontend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
      securityContext: {}
      serviceAccountName: linkops-frontend
