apiVersion: v2
name: audit-logic
description: A Helm chart for Audit Logic microservice
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
- audit
- logic
- microservice
home: https://github.com/jimjrxieb/LinkOps-MLOps
sources:
- https://github.com/jimjrxieb/LinkOps-MLOps
maintainers:
- name: jimjrxieb
  email: jimjrxieb@example.com 
