# Default values for whis-logic
replicaCount: 1

image:
  repository: ghcr.io/shadow-link-industries/whis_logic
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  role:
    create: true
    name: "whis-logic-role"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: whis-logic.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  LOG_LEVEL: "INFO"
  OPENAI_MODEL: "gpt-4"
  PROCESSING_MODE: "intelligence"
  BATCH_SIZE: "100"
  MAX_CONCURRENT_REQUESTS: "10"

secrets:
  openai:
    enabled: true
    secretName: "openai-secret"
    secretKey: "key"
  database:
    enabled: false
    secretName: "whis-db-secret"

volumes:
  data:
    enabled: true
    mountPath: "/app/data"
    persistentVolumeClaim:
      claimName: "whis-data-pvc"
  cache:
    enabled: true
    mountPath: "/app/cache"
    emptyDir: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 1000

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi 