# Default values for whis_data_input
replicaCount: 1

image:
  repository: linkops/whis_data_input
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: SERVICE_PORT
    value: "8001"

nodeSelector: {}

tolerations: []

affinity: {}
