# Default values for katie-logic
replicaCount: 1

image:
  repository: ghcr.io/shadow-link-industries/katie_logic
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  clusterRole:
    create: true
    name: "katie-logic-cluster-role"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
  - host: katie-logic.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  LOG_LEVEL: "INFO"
  OPENAI_MODEL: "gpt-4"
  K8GPT_ENABLED: "true"
  K8GPT_API_URL: "https://api.k8gpt.ai/v1/analyze"

secrets:
  openai:
    enabled: true
    secretName: "openai-secret"
    secretKey: "key"
  k8gpt:
    enabled: false
    secretName: "k8gpt-secret"
    secretKey: "api-key"

volumes:
  kubeconfig:
    enabled: true
    mountPath: "/root/.kube"
    secretName: "katie-kubeconfig"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

podSecurityContext:
  fsGroup: 1000

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
