apiVersion: v1
kind: Service
metadata:
  name: {{include "whis-logic.fullname" .}}
  labels:
    app.kubernetes.io/name: {{include "whis-logic.name" .}}
    helm.sh/chart: {{include "whis-logic.chart" .}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{include "whis-logic.name" .}}
    app.kubernetes.io/instance: {{.Release.Name}}
