<template>
  <div class="p-6 space-y-6">
    <div>
      <h1 class="text-3xl font-bold">🚀 DevSecOps Shadow Agent - Demo</h1>
      <p class="text-base text-gray-400">
        This is a demonstration of one of my Shadow Agents tailored to DevSecOps. The end goal is to have enough Orbs and Runes to complete any task given.
      </p>
    </div>

    <!-- Demo Mode Banner -->
    <div class="bg-yellow-200 text-yellow-900 text-center py-2 rounded font-semibold">
      Demo Mode: Results are simulated. No real AI or API keys required.
    </div>

    <!-- Task Submission UI -->
    <div class="border border-gray-700 rounded-2xl p-4 bg-black/30">
      <label class="text-xl font-semibold block mb-2">🧠 Task You Would Give Me</label>
      <textarea v-model="taskInput" class="w-full p-2 rounded bg-black border border-gray-700" rows="3" placeholder="e.g., create a pod named test with image nginx"></textarea>
      <div class="flex justify-end mt-2 gap-2">
        <button @click="submitTask" :disabled="loading" class="bg-purple-600 text-white px-4 py-2 rounded-2xl hover:bg-purple-700 disabled:opacity-50">
          {{ loading ? 'Searching...' : 'Search Orb' }}
        </button>
        <button @click="clearResults" class="bg-gray-700 text-white px-4 py-2 rounded-2xl hover:bg-gray-800">Clear</button>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="text-center text-gray-400 py-4">
      Searching and scoring your task...
    </div>

    <!-- Results -->
    <div v-if="matchingOrb || generatedOrb" class="space-y-4">
      <!-- Best Match Found -->
      <div v-if="matchingOrb" class="border border-green-500 bg-black/20 p-4 rounded-2xl">
        <h2 class="text-xl font-bold text-green-400">✅ Orb Found</h2>
        <p><strong>Task:</strong> {{ taskInput }}</p>
        <p><strong>Matching Orb:</strong> {{ matchingOrb.title }}</p>
        <p><strong>Confidence Score:</strong> {{ confidenceScore }}%</p>
        <div class="mt-2">
          <h3 class="text-lg font-semibold">Best Practice (Orb)</h3>
          <p><strong>Description:</strong> {{ matchingOrb.description }}</p>
          <p><strong>Tags:</strong> {{ matchingOrb.tags?.join(', ') }}</p>
        </div>
        <div class="mt-2 space-y-1">
          <p><strong>Corresponding Rune:</strong> #{{ matchingOrb.rune_id }}</p>
          <button class="mt-2 px-3 py-1 bg-gray-700 rounded hover:bg-gray-600">🔍 View Orb</button>
          <p class="italic text-yellow-400 mt-2">Runes not available in demo. They are compiled solution path scripts.</p>
          <p class="italic text-yellow-400">"Send to Agent?" → Feature not available in demo. FickNury sends tasks that are 100% autonomous to field agents.</p>
        </div>
      </div>

      <!-- AI Generated Orb -->
      <div v-else-if="generatedOrb" class="border border-blue-500 bg-black/20 p-4 rounded-2xl">
        <h2 class="text-xl font-bold text-blue-400">✨ No Orb Found - Generated Orb</h2>
        <p><strong>Task:</strong> {{ taskInput }}</p>
        <p><strong>Confidence Score:</strong> {{ confidenceScore }}%</p>
        <p class="mt-2 text-sm italic text-green-400">Sent to Whis for Learning...</p>
        <div class="mt-3 p-4 bg-gray-800 rounded">
          <h3 class="text-md font-bold text-green-300">Best Practice for: {{ taskInput }}</h3>
          <ul class="list-disc list-inside text-white">
            <li>Analyze the task requirements</li>
            <li>Identify key components and dependencies</li>
            <li>Follow industry best practices</li>
            <li>Implement with proper error handling</li>
            <li>Test and validate the solution</li>
          </ul>
          <p class="text-xs text-gray-400 mt-2">Generated by: Whis Logic | Model: Grok API</p>
        </div>
        <div class="flex gap-3 mt-2">
          <button class="px-3 py-1 rounded bg-green-700 hover:bg-green-600">✅ Approve & Save</button>
          <button class="px-3 py-1 rounded bg-red-700 hover:bg-red-600">❌ Reject</button>
        </div>
      </div>
    </div>

    <!-- How it Works -->
    <div class="border border-gray-700 rounded-2xl p-4 bg-black/30">
      <h3 class="text-xl font-semibold mb-4">
        🔬 How the DevSecOps Agent Learns
      </h3>
      <ol class="list-decimal list-inside space-y-2 text-sm">
        <li>
          <strong>Input Sources:</strong> Q&A, Info Dump, FickNury Tasks, Image
          OCR, YouTube Transcript
        </li>
        <li>
          <strong>Sanitization:</strong> Uses spaCy, Pandas, PyArrow to
          anonymize and extract structure
        </li>
        <li>
          <strong>Smithing (Orb/Rune Creation):</strong> Uses LangChain,
          scikit-learn, and OpenAI API to synthesize best practices and steps
        </li>
        <li><strong>Approval:</strong> Human-reviewed before being stored</li>
        <li>
          <strong>Enhancement:</strong> Logic injected into knowledge base for
          future retrieval
        </li>
      </ol>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import axios from 'axios'

const taskInput = ref('')
const generatedOrb = ref(null)
const matchingOrb = ref(null)
const confidenceScore = ref(null)
const loading = ref(false)

const submitTask = async () => {
  loading.value = true
  try {
    const response = await axios.post('/api/demo/search-orb', {
      task: taskInput.value
    })
    if (response.data.match) {
      matchingOrb.value = response.data.match
      confidenceScore.value = response.data.confidence
      generatedOrb.value = null
    } else {
      matchingOrb.value = null
      confidenceScore.value = response.data.confidence
      generatedOrb.value = response.data.generated_orb
    }
  } catch (error) {
    console.error(error)
    // Fallback demo response
    matchingOrb.value = null
    confidenceScore.value = 72
    generatedOrb.value = {
      title: `Best Practice for: ${taskInput.value}`,
      description: 'AI-generated best practice for the submitted task.',
      steps: [
        'Analyze the task requirements',
        'Identify key components and dependencies',
        'Follow industry best practices',
        'Implement with proper error handling',
        'Test and validate the solution',
      ],
      model: 'Grok API',
    }
  } finally {
    loading.value = false
  }
}

const clearResults = () => {
  taskInput.value = ''
  generatedOrb.value = null
  matchingOrb.value = null
  confidenceScore.value = null
}
</script>

<style scoped>
textarea:focus {
  outline: none;
  border-color: #10b981;
}
</style>
