name: Dispatch All Microservices

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'demo'
        type: choice
        options:
        - demo
        - personal
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
        - deploy
        - ci
        - destroy

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Login to GitHub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Trigger LinkOps-Arise CI
        if: inputs.action == 'ci'
        run: |
          gh workflow run ci.yml \
            --repo jimjrxieb/LinkOps-Arise \
            --ref main

      - name: Trigger LinkOps-Manifests CI
        if: inputs.action == 'ci'
        run: |
          gh workflow run ci.yml \
            --repo jimjrxieb/LinkOps-Manifests \
            --ref main

      - name: Trigger LinkOps-MLOps Deploy
        if: inputs.action == 'deploy'
        run: |
          gh workflow run deploy-aks.yml \
            --repo jimjrxieb/LinkOps-MLOps \
            --ref main \
            --field environment=${{ inputs.environment }}

      - name: Trigger LinkOps-MLOps Update Manifests
        if: inputs.action == 'deploy' && inputs.environment == 'personal'
        run: |
          gh workflow run update-manifests.yml \
            --repo jimjrxieb/LinkOps-MLOps \
            --ref main

      - name: Trigger LinkOps-Arise Destroy
        if: inputs.action == 'destroy' && inputs.environment == 'demo'
        run: |
          echo "Triggering demo environment destruction..."
          gh workflow run destroy-demo.yml \
            --repo jimjrxieb/LinkOps-Arise \
            --ref main \
            --field confirm=DESTROY

      - name: Summary
        run: |
          echo "🎯 Dispatch Summary:"
          echo "  Action: ${{ inputs.action }}"
          echo "  Environment: ${{ inputs.environment }}"
          echo "  Repositories triggered:"
          if [ "${{ inputs.action }}" = "ci" ]; then
            echo "    ✅ LinkOps-Arise CI"
            echo "    ✅ LinkOps-Manifests CI"
          elif [ "${{ inputs.action }}" = "deploy" ]; then
            echo "    ✅ LinkOps-MLOps Deploy (${{ inputs.environment }})"
            if [ "${{ inputs.environment }}" = "personal" ]; then
              echo "    ✅ LinkOps-MLOps Update Manifests"
            fi
          elif [ "${{ inputs.action }}" = "destroy" ]; then
            if [ "${{ inputs.environment }}" = "demo" ]; then
              echo "    ⚠️  Demo destruction triggered"
            else
              echo "    ❌ Destruction not allowed for ${{ inputs.environment }}"
            fi
          fi 