name: CI - Ficknury Evaluator

on:
  push:
    paths:
      - "shadows/ficknury_evaluator/**"
  pull_request:
    paths:
      - "shadows/ficknury_evaluator/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shadows/ficknury_evaluator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black formatting check
        run: black . --check --diff

      - name: Run Flake8 linting
        run: flake8 . --max-line-length=88 --extend-ignore=E203

      - name: Run tests
        run: pytest tests/ -v || true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: shadows/ficknury_evaluator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shadow-link-industries/ficknury-evaluator:latest
            ghcr.io/shadow-link-industries/ficknury-evaluator:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 