name: Ficknury CI/CD

on:
  push:
    paths:
      - 'services/ficknury/**'
      - '.github/workflows/ficknury.yml'

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Bandit Scan
        run: bandit -r services/ficknury -ll

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Trivy Filesystem Scan
        run: trivy fs services/ficknury --exit-code 1 --severity CRITICAL

      - name: TruffleHog Secrets Scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD

  gitguardian_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitGuardian Secrets Scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sonarcloud:
    needs: [sast, gitguardian_scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: services/ficknury
          organization: ${{ secrets.SONAR_ORG }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    needs: [sast, gitguardian_scan, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Docker Image
        run: docker build -t linksrobot/ficknury:latest ./services/ficknury

      - name: Trivy Image Scan
        run: trivy image linksrobot/ficknury:latest --exit-code 1 --severity CRITICAL

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_CRED }}

      - name: Push Docker Image
        run: docker push linksrobot/ficknury:latest 