name: Frontend Build CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yml'

jobs:
  gitguardian_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitGuardian Secrets Scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  docker:
    needs: gitguardian_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t linksrobot/frontend:latest ./frontend

      - name: Trivy Image Scan
        run: trivy image linksrobot/frontend:latest --exit-code 1 --severity CRITICAL

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_CRED }}

      - name: Push Docker Image
        run: docker push linksrobot/frontend:latest

  sonarcloud:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java (required for SonarCloud)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }} 