name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t linksrobot/frontend:latest ./frontend

      - name: Trivy Image Scan
        run: trivy image linksrobot/frontend:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_CRED }}

      - name: Push Docker Image
        run: docker push linksrobot/frontend:latest 