name: Whis CI/CD

on:
  push:
    paths:
      - 'services/whis/**'
      - '.github/workflows/whis.yml'

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Bandit Scan
        run: bandit -r services/whis -ll

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Trivy Filesystem Scan
        run: trivy fs services/whis --exit-code 1 --severity CRITICAL

      - name: TruffleHog Secrets Scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD

  gitguardian_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitGuardian Secrets Scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  sonarcloud:
    needs: [sast, gitguardian_scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java (required for SonarCloud)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: services/whis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}

  docker:
    needs: [sast, gitguardian_scan, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Docker Image
        run: docker build -t linksrobot/whis:latest ./services/whis

      - name: Trivy Image Scan
        run: trivy image linksrobot/whis:latest --exit-code 1 --severity CRITICAL

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_CRED }}

      - name: Push Docker Image
        run: docker push linksrobot/whis:latest 