apiVersion: v2
name: frontend
description: A Helm chart for LinkOps Frontend (Vue3)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
- frontend
- vue3
- linkops
home: https://github.com/jimjrxieb/LinkOps-MLOps
sources:
- https://github.com/jimjrxieb/LinkOps-MLOps
maintainers:
- name: jimjrxieb
  email: jimjrxieb@example.com 