# Default values for whis-logic
replicaCount: 1

image:
  repository: linkops/whis-logic
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8003

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: SERVICE_PORT
    value: "8003"
  - name: GROK_API_KEY
    valueFrom:
      secretKeyRef:
        name: grok-api-secret
        key: api-key

nodeSelector: {}

tolerations: []

affinity: {}
