# Default values for whis-logic
replicaCount: 1

image:
  repository: linksrobot/demo-whis-logic
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8003

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  LOG_LEVEL: "INFO"
  SERVICE_PORT: "8003"
  GROK_SECRET_NAME: "grok-api-secret"
  GROK_SECRET_KEY: "api-key"

nodeSelector: {}

tolerations: []

affinity: {}
